import React from "react";
import "./TermsAndConditions.css";

const TermsAndConditions = () => {
  return (
    <div className="terms-and-conditions text-center">
      <h1>Terms and Conditions</h1>
      <p>
        These terms and conditions ("Terms") govern your use of the Paisa
        monitor affiliate marketing app ("App"). This App is owned and operated
        by Paisa Monitor. Throughout the App, the terms (“paisa monitor”, “us”,
        “we”, or “our”) offers affiliate marketing through this App (“Company”.)
        By using the App, you agree to be bound by these Terms. Paisa Monitor a
        company registered in India and operating within the ambit of the laws
        of the India and European Union (EU),
      </p>
      <h2>Membership</h2>
      <p>
        1.1. To become a member of the App, you must register and provide
        accurate and complete information about yourself as prompted by the
        registration form.
        <br />
        1.2. You must be at least 14 years old to become a member.
        <br />
        1.3. Membership is free and can be terminated by either you or the
        Company at any time.
      </p>
      <h2>Referral Code and Advertising Revenue</h2>
      <p>
        2.1. As a member, you will receive a unique referral code that you can
        share with others.
        <br />
        2.2. When a user signs up for the App using your referral code, you will
        be eligible to receive a part of the advertising revenue generated by
        that user's activities on the App.
        <br />
        2.3. The percentage of advertising revenue that you will receive can
        vary and is subject to change without prior notice.
        <br />
        2.4. The Company reserves the right to modify or terminate the referral
        program at any time without prior notice.
      </p>
      <h2>Payment</h2>
      <p>
        3.1. Payment for advertising revenue earned through your referral code
        will be made to you after 30 days.
        <br />
        3.2. Payment will be made to the payment method specified in your
        account profile.
        <br />
        3.3. The Company is not responsible for any fees or charges that may be
        incurred by you in connection with the receipt of payments.
      </p>
      <h2>Prohibited Activities</h2>
      <p>
        4.1. You may not engage in any fraudulent or deceptive activities in
        connection with the App.
        <br />
        4.2. You may not engage in any activity that violates any applicable law
        or regulation.
        <br />
        4.3. You may not engage in any activity that interferes with the
        operation of the App or with the rights of other users.
        <br />
        4.4. The Company reserves the right to terminate your membership and/or
        withhold payment if you engage in any prohibited activities.
      </p>
      <h2>Intellectual Property</h2>
      <p>
        5.1. The App and all content and materials contained therein are the
        property of the Company and/or its affiliates and licensors.
        <br />
        5.2. You may not use any content or materials from the App without the
        prior written consent of the Company.
      </p>
      <h2>Disclaimer of Warranties</h2>
      <p>
        6.1. The App is provided "as is" and without warranty of any kind,
        express or implied.
        <br />
        6.2. The Company does not warrant that the App will be error-free or
        uninterrupted.
        <br />
        6.3. The Company disclaims all warranties, including without limitation,
        implied warranties of merchantability, fitness for a particular purpose,
        and non-infringement.
      </p>
      <h2>Limitation of Liability</h2>
      <p>
        7.1. In no event shall the Company be liable for any indirect,
        incidental, special, or consequential damages arising out of or in
        connection with the App, including without limitation, damages for loss
        of profits, goodwill, use, data, or other intangible losses.
        <br />
        7.2. The Company's total liability to you for any and all claims arising
        out of or in connection with the App shall not exceed the amount of
        advertising revenue paid to you by the Company.
      </p>
      <h2>Indemnification</h2>
      <p>
        8.1. You agree to indemnify and hold the Company harmless from any and
        all claims, damages, expenses, and liabilities arising out of or in
        connection with your use of the App.
      </p>
      <h2>Governing Law and Jurisdiction</h2>
      <p>
        9.1. These Terms shall be governed by and construed in accordance with
        the laws of India.
        <br />
        9.2. Any disputes arising out of or in connection with these Terms shall
        be resolved through arbitration in accordance with the rules of the
        Indian Arbitration and Conciliation Act, 1996.
      </p>
      <h6>
        Question, comment and feedback, contact us support@paisamonitor.com
      </h6>
    </div>
  );
};

export default TermsAndConditions;
